spring:
    jpa:
      hibernate:
        ddl-auto: update
      defer-datasource-initialization: true
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
      driverClassName: org.h2.Driver
      username: sa
      password: 1
    application:
        name: spring-prueba-tecnica



password:
    pattern: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,20}$

jwt:
    secret: 586E3272357538782F413F4428472B4B6250655368566B597033733676397924
    expiration: 86400000